// <auto-generated />
using System;
using ERP.Modules.Accounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Modules.Accounting.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260803035630_AddVoucherAttachment")]
    partial class AddVoucherAttachment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Modules.Accounting.Models.AccountTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AccountTitles", "acc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Code = "1101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 698, DateTimeKind.Utc).AddTicks(9430),
                            IsActive = true,
                            Level = 1,
                            Name = "現金及約當現金"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Code = "1102",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "銀行存款"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Code = "1103",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "應收帳款"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Code = "1104",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "存貨"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Code = "1401",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "不動產、廠房及設備"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Code = "2101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "應付帳款"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Code = "2102",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(210),
                            IsActive = true,
                            Level = 1,
                            Name = "應付薪資"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Code = "2103",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "應付稅額"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Code = "2201",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "長期借款"
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Code = "3101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "普通股股本"
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            Code = "3201",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "保留盈餘"
                        },
                        new
                        {
                            Id = 12,
                            Category = 4,
                            Code = "4101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "銷貨收入"
                        },
                        new
                        {
                            Id = 13,
                            Category = 4,
                            Code = "4201",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "勞務收入"
                        },
                        new
                        {
                            Id = 14,
                            Category = 5,
                            Code = "5101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "銷貨成本"
                        },
                        new
                        {
                            Id = 15,
                            Category = 5,
                            Code = "6101",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "薪資支出"
                        },
                        new
                        {
                            Id = 16,
                            Category = 5,
                            Code = "6201",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "租金支出"
                        },
                        new
                        {
                            Id = 17,
                            Category = 5,
                            Code = "6301",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "水電瓦斯費"
                        },
                        new
                        {
                            Id = 18,
                            Category = 5,
                            Code = "6401",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(220),
                            IsActive = true,
                            Level = 1,
                            Name = "文具用品"
                        });
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AccountTitleId")
                        .HasColumnType("int");

                    b.Property<string>("ApiClientId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ApiType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountTitleId");

                    b.ToTable("BankAccounts", "acc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "○○企業股份有限公司",
                            AccountNumber = "0808-988-123456",
                            AccountTitleId = 2,
                            ApiClientId = "ESUN_ERP_CLIENT_2026",
                            ApiEndpoint = "https://api.esunbank.com.tw/open-banking/v1",
                            ApiType = 2,
                            Balance = 1280500m,
                            BankCode = "808",
                            BankName = "玉山銀行",
                            BranchName = "營業部",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(4050),
                            Currency = "TWD",
                            IsActive = true,
                            LastSyncedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(5770)
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "○○企業股份有限公司",
                            AccountNumber = "0130-100-888999",
                            AccountTitleId = 2,
                            ApiClientId = "CATHAY_SANDBOX_KEY",
                            ApiEndpoint = "https://sandbox.cathaybk.com.tw/v1",
                            ApiType = 1,
                            Balance = 650000m,
                            BankCode = "013",
                            BankName = "國泰世華銀行",
                            BranchName = "敦南分行",
                            CreatedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(5990),
                            Currency = "TWD",
                            IsActive = true,
                            LastSyncedAt = new DateTime(2026, 8, 3, 3, 56, 29, 699, DateTimeKind.Utc).AddTicks(5990)
                        });
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings", "acc");

                    b.HasData(
                        new
                        {
                            Key = "Accounting:ClosedUntilDate",
                            Value = "2000-01-01"
                        });
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers", "acc");
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.VoucherDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTitleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDebit")
                        .HasColumnType("bit");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountTitleId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherDetails", "acc");
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.AccountTitle", b =>
                {
                    b.HasOne("ERP.Modules.Accounting.Models.AccountTitle", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.BankAccount", b =>
                {
                    b.HasOne("ERP.Modules.Accounting.Models.AccountTitle", "AccountTitle")
                        .WithMany()
                        .HasForeignKey("AccountTitleId");

                    b.Navigation("AccountTitle");
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.VoucherDetail", b =>
                {
                    b.HasOne("ERP.Modules.Accounting.Models.AccountTitle", "AccountTitle")
                        .WithMany()
                        .HasForeignKey("AccountTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Modules.Accounting.Models.Voucher", "Voucher")
                        .WithMany("Details")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountTitle");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ERP.Modules.Accounting.Models.Voucher", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
